name: wamp_client
description: A library for Dart WAMP client.
version: 0.2.1
homepage: https://github.com/kkazuo/dart-wamp-client
author: Koga Kazuo <obiwanko@me.com>

environment:
  sdk: '>=2.0.0 <3.0.0'
  
dependencies:
  msgpack2:
    git: https://github.com/butlermatt/msgpack2
